### ISSUE TITLE
Datatable doesn't remove the old previous year selected title corretly

### ISSUE THREAD

**Issue by bastienvinh** [CivicTechTO/budgetpedia-frontend#3]
When we change year we can see the title of the previous year.

This is what is happening when I selected another year : 
![first-error](https://user-images.githubusercontent.com/5178193/32507471-7d9c83d2-c3b5-11e7-80f3-3550dd2caf80.png)

When I selected 2017 and after 2016, it is what happens.

Now, what happens, when I select 2007:
![second-error](https://user-images.githubusercontent.com/5178193/32507513-9f6cc828-c3b5-11e7-944b-1fc25c8f19a1.png)

We two titles that we don't want.

**Comment by HenrikBechmann** [comment]
"Inflation adjusted to 2017 $" is a critical piece of information, we could probably do without the "up to 2016" though...

**Comment by HenrikBechmann** [comment]
removed "up to 2016". That's much easier to read, thanks!

technically, when we put in 2018 amounts, that statement will be slightly misleading without the ‘up to 2016’ because during the transition the 2018 $ are not inflation adjusted back to 2017 $. But the advantages of the shorter statement probably outweigh that technical detail.
